version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: vitaliafit_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vitaliafit_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data